# Lecture 2: tensorflow ops

**Useful links:** 
1. [Lecture note](http://web.stanford.edu/class/cs20si/lectures/notes_02.pdf);
2. [Leture slides](http://web.stanford.edu/class/cs20si/lectures/slides_02.pdf);

# Part 1

## Fun with TensorBoard
TensorFlow = TensorFlow + TensorBoard + TensorServing

TensorBoard is graph visualzation software included with any standard TensorFlow installation.

When a user perform certain operations in a TensorBoard-activated TensorFlow program, these operations are exported to an event file. TensorBoard is able to convert these event files to graphs that give insight into a model's behavior.

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
g = tf.Graph()
with g.as_default():
    a = tf.constant(2)
    b = tf.constant(3)
    x = tf.add(a, b)

In [3]:
with tf.Session(graph=g) as sess:
    x = sess.run(x)
    print(x)

5


In [4]:
print(sess)
writer = tf.summary.FileWriter('./graphs_test1', sess.graph)

In [5]:
g = tf.Graph()
with g.as_default():
    a = tf.constant(2)
    b = tf.constant(3)
    x = tf.add(a, b)

In [6]:
with tf.Session(graph=g) as sess:
    writer = tf.summary.FileWriter('./graphs_test2', sess.graph)
    x = sess.run(x)
    print(x)
writer.close()

5


### Display logs by tensorboard

In [7]:
# $ tensorboard --logdir="./graphs_test1"
# $ tensorboard --logdir="./graphs_test2" -port 6007 # to avoid port is in use

Standford note suggest we to add the summary line right before the running loop, however,
I try to summary afer session being closed. Both of them get the same log......I didn't get the purpose of this suggestion yet.

### Name the ops

In [8]:
g = tf.Graph()
with g.as_default():
    a = tf.constant([2, 2], name='a')
    b = tf.constant([3, 6], name='b')
    x = tf.add(a, b, name='add')

In [9]:
# tf.Session.run(fetches, feed_dict=None, options=None, run_metadata=None)
with tf.Session(graph=g) as sess:
    writer = tf.summary.FileWriter('./graphs', sess.graph)
    x = sess.run(x)
    print(x)
writer.close()
# display your log again to see the name you had explicitly assigned.

[5 8]


### Note:
If you've run your code several times, there will be muliple event files, TF will show only the lastest graph and display the warning of multiple event files. To get rid of the warning, delete all the event files you no longer need.

## Constant types

tf.convert_to_tensor(value, dtype=None, name=None, preferred_dtype=None)

All standard Python op constructors apply this function to each of their Tensor-valued inputs, which allows those ops to accept numpy arrays, Python lists, and scalars in addition to Tensor objects.
https://www.tensorflow.org/api_docs/python/tf/
https://www.tensorflow.org/api_docs/python/tf/convert_to_tensor

In [10]:
# tf.constant(value, dtype=None, shape=None, name='Const', verify_shape=False)
# constant of 1d tensor (vector)
a = tf.constant([2, 2], name='vector')
print(a)

# constant of 2*2 tensor (matrix)
b = tf.constant([[0, 1], [2, 3]], name='b')
print(b)

Tensor("vector:0", shape=(2,), dtype=int32)
Tensor("b:0", shape=(2, 2), dtype=int32)


### You can creat tensors whose elements are of a specific value
Note the similarity to numpy.zeros, numpy.zeros_like, numpy.ones, numpy.ones_like

In [11]:
# tf.zeros(shape, dtype=tf.float32, name=Nome)
# shape: Either a list of integers, or a 1-D Tensor of type int32
# create a tensor of shape and all elements are zeros
a = tf.zeros([2, 3], tf.int32)
print(a)
with tf.Session() as sess:
    a = sess.run(a)
    print(a)

Tensor("zeros:0", shape=(2, 3), dtype=int32)
[[0 0 0]
 [0 0 0]]


In [12]:
# tf.zeros_like(tensor, dtype=None, name=None, optimize=True)
# Creates a tensor of shape and type(unless type is specified) as the input_tensor but
# all elements are zeros
a = tf.constant([[0, 1],
                 [2, 3],
                 [4, 5]])
b = tf.zeros_like(a)
print(b)
with tf.Session() as sess:
    b = sess.run(b)
    print(b)

Tensor("zeros_like:0", shape=(3, 2), dtype=int32)
[[0 0]
 [0 0]
 [0 0]]


In [13]:
# tf.ones(shape, dtype=tf.float32, name=None)
# create a tensor of shape and all elements are ones
a = tf.ones([2, 3], tf.int32)
print(a)
with tf.Session() as sess:
    a = sess.run(a)
    print(a)

Tensor("ones:0", shape=(2, 3), dtype=int32)
[[1 1 1]
 [1 1 1]]


In [14]:
# tf.ones_like(tensor, dtype=None, name=None, optimize=True)
# create a tensor of shape and type (unless type is specified) as the input_tensor but all
# elements are ones
a = tf.constant([[0, 1],
                 [2, 3],
                 [4, 5]])
b = tf.ones_like(a)
print(b)
with tf.Session() as sess:
    b = sess.run(b)
    print(b)

Tensor("ones_like:0", shape=(3, 2), dtype=int32)
[[1 1]
 [1 1]
 [1 1]]


In [15]:
# tf.fill(dims, value, name=None)
# create a tensor filled with a scalar value
a = tf.fill([2, 3], 8)
print(a)
with tf.Session() as sess:
    a = sess.run(a)
    print(a)

Tensor("Fill:0", shape=(2, 3), dtype=int32)
[[8 8 8]
 [8 8 8]]


### You can create constants that are sequences

In [16]:
# tf.linspace(start, stop, num, name=None)
# create a sequence of num evenly-spaced values are generated beginning at start. If num>1
# the values in the sequence increase by stop - start / num -1, so that the last one is
# exactly stop
# start, stop, num must be scalars
# start, stop Must be one of the following types: float32, float64, num: int32, int64
# comparable to but sligtly different from numpy.linspace
# numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

a = tf.linspace(10.0, 13.0, 4, name='linspace')
print(a)
with tf.Session() as sess:
    a = sess.run(a)
    print(a)

Tensor("linspace:0", shape=(4,), dtype=float32)
[ 10.  11.  12.  13.]


In [17]:
# tf.range(start, limit=None, delta=1, dtype=None, name='range')
# Creates a sequence of numbers that begins at start and extends by increments of delta
# up to but not including limit
# Like the Python builtin range, start defaults to 0, so that range(n) = range(0, n)
a = tf.range(3, 18, 3)
print(a)
with tf.Session() as sess:
    a = sess.run(a)
    print(a)

Tensor("range:0", shape=(5,), dtype=int32)
[ 3  6  9 12 15]


In [18]:
# a = tf.range(3, 1, -0.5) maybe for dtype reason this line may raise error
a = tf.range(3.0, 1.0, -0.5)
print(a)
with tf.Session() as sess:
    a = sess.run(a)
    print(a)

Tensor("range_1:0", shape=(4,), dtype=float32)
[ 3.   2.5  2.   1.5]


In [19]:
a = tf.range(5)
print(a)
with tf.Session() as sess:
    a = sess.run(a)
    print(a)

Tensor("range_2:0", shape=(5,), dtype=int32)
[0 1 2 3 4]


#### Note that unlike NumPy or Python sequences, TensorFlow sequences are not iterable

In [20]:
for i in np.linspace(0, 10, 4):
    print(i)

0.0
3.33333333333
6.66666666667
10.0


In [ ]:
# tf.linspace(0, 10, 4)
# TypeError: Value passed to parameter 'start' has DataType int32 not in list of allowed 
# values: float32, float64
for i in tf.linspace(0.0, 10.0, 4):
    print(i)
# TypeError: 'Tensor' object is not iterable

In [22]:
for i in range(4):
    print(i)

0
1
2
3


In [ ]:
for i in tf.range(4):
    print(i)
# TypeError: 'Tensor' object is not iterable.

### You can also generate random constants from certain distributions

In [ ]:
# tf.random_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)
# tf.truncated_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)
# tf.random_uniform(shape, minval=0, maxval=None, dtype=tf.float32, seed=None, name=None)
# tf.random_shuffle(value, seed=None, name=None)
# tf.random_crop(value, size, seed=None, name=None)
# tf.multinomial(logits, num_samples, seed=None, name=None)
# tf.random_gamma(shape, alpha, beta=None, dtype=tf.float32, seed=None, name=None)
# tf.set_random_seed(seed) # Operations that rely on a random seed actually derive 
#it from two seeds: the graph-level and operation-level seeds. This sets the 
# graph-level seed.

https://www.tensorflow.org/api_docs/python/tf/set_random_seed

In [23]:
g = tf.Graph()
with g.as_default():
    tf.set_random_seed(123)
    a = tf.random_uniform([2, 3], minval=0.0, maxval=10.0)
    b = tf.random_normal([2, 3], mean=0.0, stddev=4.0)

print("Session 1")
with tf.Session(graph=g) as sess1:
    print('a1')
    print(sess1.run(a))
    print('a2')
    print(sess1.run(a))
    print('b1')
    print(sess1.run(b))
    print('b2')
    print(sess1.run(b))

print("Session 2")
with tf.Session(graph=g) as sess2:
    print('a1')
    print(sess2.run(a))
    print('a2')
    print(sess2.run(a))
    print('b1')
    print(sess2.run(b))
    print('b2')
    print(sess2.run(b))

Session 1
a1
[[ 3.10000658  7.7726078   4.36233521]
 [ 4.33057308  0.70752025  5.44950485]]
a2
[[ 4.27698374  2.59973884  8.42744923]
 [ 2.16902852  1.45320177  5.87610722]]
b1
[[-0.20380068  1.02053642  0.83243173]
 [ 0.12789387 -3.15761328  6.83167458]]
b2
[[-3.93487716  5.25653267  2.17159677]
 [ 0.12227363  8.25422764 -7.55906105]]
Session 2
a1
[[ 3.10000658  7.7726078   4.36233521]
 [ 4.33057308  0.70752025  5.44950485]]
a2
[[ 4.27698374  2.59973884  8.42744923]
 [ 2.16902852  1.45320177  5.87610722]]
b1
[[-0.20380068  1.02053642  0.83243173]
 [ 0.12789387 -3.15761328  6.83167458]]
b2
[[-3.93487716  5.25653267  2.17159677]
 [ 0.12227363  8.25422764 -7.55906105]]


In [24]:
a = tf.constant(np.random.uniform(low=0.0, high=10.0, size=(2, 3)))
b = tf.constant(np.random.normal(loc=0.0, scale=1.0, size=(2,3)))
with tf.Session() as sess:
    a1, b1 = sess.run([a, b])
    a2, b2 = sess.run([a, b])
    print(a1)
    print(b1)
    print(a2)
    print(b2)

[[ 6.77753503  5.03207802  5.6798031 ]
 [ 3.92553631  2.4071212   9.85233095]]
[[ 1.28136131 -0.3047094  -0.75538523]
 [-1.5691671  -1.22085975  0.65354131]]
[[ 6.77753503  5.03207802  5.6798031 ]
 [ 3.92553631  2.4071212   9.85233095]]
[[ 1.28136131 -0.3047094  -0.75538523]
 [-1.5691671  -1.22085975  0.65354131]]


### Math Operations
https://www.tensorflow.org/api_guides/python/math_ops

In [25]:
a = tf.constant([3, 6])
b = tf.constant([2, 2])
c_0 = tf.add(a, b)
c_1 = tf.add_n([a, b, b])
c_2 = tf.multiply(a, b) # element wise
c_3 = tf.matmul(tf.reshape(a, [1, 2]), tf.reshape(b, [2, 1]))
c_4 = tf.div(a, b)
c_5 = tf.mod(a, b)
with tf.Session() as sess:
    c_0, c_1, c_2, c_3, c_4, c_5 = sess.run([c_0, c_1, c_2, c_3, c_4, c_5])
    print(c_0)
    print(c_1)
    print(c_2)
    print(c_3)
    print(c_4)
    print(c_5)

[5 8]
[ 7 10]
[ 6 12]
[[18]]
[1 3]
[1 0]


### Data Types

In [26]:
a_0 = 19
a_1 = tf.zeros_like(a_0)
a_2 = tf.ones_like(a_0)
b_0 = [b"apple", b"peach", b"grape"]
b_1 = tf.zeros_like(b_0)
#b_2 = tf.ones_like(b_0) # TypeError: Expected string, got 1 of type 'int' instead

c_0 = [[True, False, False],
       [False, False, True],
       [False, True, False]] # treated as a 2-d tensor, or "matrix"
c_1 = tf.zeros_like(c_0)
c_2 = tf.ones_like(c_0)
with tf.Session() as sess:
    a_1, a_2, b_1, c_1, c_2 = sess.run([a_1, a_2, b_1, c_1, c_2])
    print(a_1)
    print(a_2)
    print(b_1)
    #print(b_2)
    print(c_1)
    print(c_2)

0
1
['' '' '']
[[False False False]
 [False False False]
 [False False False]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


### Variables
Constants have been fun, but I think now you guys are old enough to how about variables.
The difference between a constant and variable:
1. A constant is constant. A variable can be assigned to, its value can be changed.
2. A constant's value is stored in the graph and its value is replicated wherever the graph is loads. A variable is stored separately, and may live on a parameter server.

In [27]:
g = tf.Graph()
with g.as_default():
    my_const = tf.constant([1.0, 2.0], name='my_const')
    print(tf.get_default_graph().as_graph_def())

node {
  name: "my_const"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: 2
          }
        }
        tensor_content: "\000\000\200?\000\000\000@"
      }
    }
  }
}
versions {
  producer: 21
}



#### Declare variables

In [28]:
# create variable a with scalar value
a = tf.Variable(2, name='scalar')
print(a)
# create variable b as a vector
b = tf.Variable([2, 3], name='vector')
print(b)
# create variable c as a 2*2 matrix
c = tf.Variable([[0, 1], [2, 3]], name='matrix')
print(c)
# create variable W as 784*10 tensor, filled with zeros
W = tf.Variable(tf.zeros([784, 10]))
print(W)

Tensor("scalar/read:0", shape=(), dtype=int32)
Tensor("vector_1/read:0", shape=(2,), dtype=int32)
Tensor("matrix/read:0", shape=(2, 2), dtype=int32)
Tensor("Variable/read:0", shape=(784, 10), dtype=float32)


In [29]:
g = tf.Graph()
with g.as_default():
    x = tf.Variable(2, name='scalar')
print(g.get_operations())
print(g.version)

with tf.Session(graph=g) as sess:
    sess.run(x.initializer)
    print(sess.run(x.assign_add(3)))

[<tf.Operation 'scalar/initial_value' type=Const>, <tf.Operation 'scalar' type=VariableV2>, <tf.Operation 'scalar/Assign' type=Assign>, <tf.Operation 'scalar/read' type=Identity>]
4
5


In [30]:
# You have to initialize variables before using them
init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)

In [31]:
init_ab = tf.variables_initializer([a, b], name='init_ab')
with tf.Session() as sess:
    sess.run(init_ab)

In [32]:
# create variable W as 784*10 tensor, filled with zeros
W = tf.Variable(tf.zeros([784, 10]))
with tf.Session() as sess:
    sess.run(W.initializer)
# another way to initialize a variable is to restore it from a save file

#### Evaluate values of variables

In [33]:
# W is a random 700*100 variable object
W = tf.Variable(tf.truncated_normal([700, 10]))
with tf.Session() as sess:
    sess.run(W.initializer)
    print(W)

Tensor("Variable_2/read:0", shape=(700, 10), dtype=float32)


In [34]:
# to get the value of a variable, we need to evaluate it using eval()
W = tf.Variable(tf.truncated_normal([700, 10]))
with tf.Session() as sess:
    sess.run(W.initializer)
    print(W.eval())

[[-0.87107468  0.26141784  1.52498627 ...,  0.90238583  0.79691088
  -0.06048778]
 [ 0.68131208 -0.42437628 -0.04228624 ..., -1.3219763   0.42711928
  -1.3788898 ]
 [-1.32859874 -0.52924287  0.03264492 ...,  0.25225312 -0.655994
  -1.28667557]
 ..., 
 [ 0.68829215  1.28704309  0.66447854 ...,  1.02221203 -0.43233114
   1.59204376]
 [ 1.27488673 -1.16340578  0.05163746 ..., -1.20619512  0.31666392
   1.4724524 ]
 [-0.47545099 -1.50535309 -1.44748247 ...,  0.2528604  -1.66840899
   0.74078834]]


#### Assign values to variables
we can assign a value to a variable using tf.Variable.assign()

In [35]:
W = tf.Variable(10)
W.assign(100)
with tf.Session() as sess:
    sess.run(W.initializer)
    print(W.eval())

10


In [36]:
W = tf.Variable(10)
assign_op = W.assign(100)
with tf.Session() as sess:
    sess.run(assign_op)
    print(W.eval())
# Note that we don't have initialize W in this case, because assign() does it for us.
# In fact, initializer op is the assign op that assigns the variable's initial value
# to the variable itself.
# in the source code
# self._initializer_op = state_ops.assign(self._variable, self._initial_value,
#                                        validate_shape=validate_shape).op

100


In [37]:
# Intersting example
# create a variable whose original value is 2
a = tf.Variable(2, name='scalar')
# assign a*2 to a and call that op a_times_two
a_times_two = a.assign(a * 2)

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    # have to initialize a, because a_times_two op depends on the value of a
    print(sess.run(a_times_two)) # >> 4
    print(sess.run(a_times_two)) # >> 8
    print(sess.run(a_times_two)) # >> 16

4
8
16


In [38]:
W = tf.Variable(10)

with tf.Session() as sess:
    sess.run(W.initializer)
    print(sess.run(W.assign_add(10)))
    print(sess.run(W.assign_sub(2)))

20
18


In [39]:
W = tf.Variable(10)

sess1 = tf.Session()
sess2 = tf.Session()

sess1.run(W.initializer)
sess2.run(W.initializer)

print(sess1.run(W.assign_add(10)))
print(sess2.run(W.assign_sub(2)))

print(sess1.run(W.assign_add(100)))
print(sess2.run(W.assign_sub(50)))

sess1.close()
sess2.close()

20
8
120
-42


In [40]:
# W is a random 700*100 tensor
W = tf.Variable(tf.truncated_normal([700, 10]))
U = tf.Variable(W * 2)
init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(W.initializer)
    sess.run(U.initializer)
    print(W.eval())
    print(U.eval())
# In this case, you should use initialized_value() to make sure that W is initialized
# before its value is used to initialize W

[[ 0.15774222  1.6848619   0.75867641 ...,  0.70471513  0.45140892
   1.1388737 ]
 [-1.90446675  0.40704605 -0.52457744 ...,  1.38665187  0.0540167
  -0.13397592]
 [-1.99462855  0.87634164  0.38599205 ..., -0.44720611 -1.18347108
  -1.10491443]
 ..., 
 [ 0.05733988 -0.88313168  1.40067708 ...,  0.46848473  0.86937541
   1.65061593]
 [ 0.09700993 -0.68789995  1.15506804 ..., -0.14402924  0.50634795
  -0.30204296]
 [ 0.13493772  1.31803548 -1.11376512 ..., -0.86277169  0.96434861
   0.03455852]]
[[ 0.31548443  3.3697238   1.51735282 ...,  1.40943027  0.90281785
   2.27774739]
 [-3.8089335   0.8140921  -1.04915488 ...,  2.77330375  0.1080334
  -0.26795185]
 [-3.9892571   1.75268328  0.7719841  ..., -0.89441222 -2.36694217
  -2.20982885]
 ..., 
 [ 0.11467977 -1.76626337  2.80135417 ...,  0.93696946  1.73875082
   3.30123186]
 [ 0.19401987 -1.37579989  2.31013608 ..., -0.28805849  1.01269591
  -0.60408592]
 [ 0.26987544  2.63607097 -2.22753024 ..., -1.72554338  1.92869723
   0.06911704]]


### InteractiveSession
You sometimes see InteractiveSession instead of Session. The only difference is an
InteractiveSession makes itself the default session so you can call run() or eval()
without explicitly call the session. This is convenient in interactive shells and IPyhon notebooks, as it avoids having to pass an explicit Session object to run ops. However, it is complicated when you have multiple sessions to run.

tf.get_default_session() returns the default session for the current thread. The returned Session will be the innermost session on which a Session or Session.as_default() context has been entered.

In [41]:
sess = tf.InteractiveSession()
a = tf.constant(5.0)
b = tf.constant(6.0)
c = a * b
# we can just use 'c.eval()' without passing 'sess'
print(c.eval())
sess.close()

30.0


### Control Dependencies

In [ ]:
# # your graph g have 5 ops: a, b, c, d, e
# with g.control_dependencies([a, b, c]):
#     # 'd' and 'e' will only run after 'a', 'b', and 'c' have executed
#     d = ...
#     e = ...

### Placeholders and feed_dict
https://www.tensorflow.org/api_docs/python/tf/placeholder

In [ ]:
# to define a placeholder, we use:
# tf.placeholder(dtype, shape=None, Name=None)

# create a placeholder of type float 32-bit, shape is a vector of 3 elements
a = tf.placeholder(tf.float32, shape=[3])

# create a constant of type float 32-bit, shape is a vector of 3 elements
b = tf.constant([5, 5, 5], tf.float32)

# use the placeholder as you would a constant or variable
c = a + b # short for tf.add(a, b)

# If we try to fetch c, we will run into error.

with tf.Session() as sess:
    print(sess.run(c))
# InvalidArgumentError (see above for traceback): You must feed a value for placeh
# older tensor 'Placeholder' with dtype float and shape [3]

In [46]:
# to define a placeholder, we use:
# tf.placeholder(dtype, shape=None, Name=None)
g = tf.Graph()
with g.as_default():
    # create a placeholder of type float 32-bit, shape is a vector of 3 elements
    a = tf.placeholder(tf.float32, shape=[3])

    # create a constant of type float 32-bit, shape is a vector of 3 elements
    b = tf.constant([5, 5, 5], tf.float32)

    # use the placeholder as you would a constant or variable
    c = a + b # short for tf.add(a, b)

# If we try to fetch c, we will run into error.

with tf.Session(graph=g) as sess:
    writer = tf.summary.FileWriter('./my_graph', sess.graph)
    print(sess.run(c, feed_dict={a:[1, 2, 3]}))

[ 6.  7.  8.]


In [48]:
# we can feed as any data points to placeholder as we want by iterating through the data
# set and feed in the value one at a time.
# you can feed values to tensors that aren't placeholders. Any tensors that feedable can
# be fed. To check if a tensor is feedable or not, use:
# tf.Graph.is_feedable(tensor)

# create Operations, Tensors, etc(using the default graph)
a = tf.add(2, 5)
b = tf.multiply(a, 3)

with tf.Session() as sess:
    replace_dict = {a: 15}
    print(sess.run(b, feed_dict=replace_dict))
# feed_dict can be extremely useful to test your model. When you have a large graph and 
# just want to test out certain parts, you can provide dummy values so TensorFlow won't
# waste time doing unnecessary computaions

45


### The trap of lazy loading

TensorFlow, it means you defer creating an op until you need to compute it. For example,
this is normal loading: you create the op z when you assemble the graph.

In [56]:
g = tf.Graph()
with g.as_default():
    x = tf.Variable(10, name='x')
    y = tf.Variable(20, name='y')
    z = tf.add(x, y)

with tf.Session(graph=g) as sess:
    sess.run(tf.global_variables_initializer())
    for _ in range(10):
        sess.run(z)
    writer = tf.summary.FileWriter('./graph_1', sess.graph)
    writer.close()
    #print(sess.graph.get_operations())
    print(sess.graph.version)
    print(sess.graph.as_graph_def())
# The protobuf for the graph in normal loading has only 1 node “Add”

10
node {
  name: "x/initial_value"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 10
      }
    }
  }
}
node {
  name: "x"
  op: "VariableV2"
  attr {
    key: "container"
    value {
      s: ""
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
      }
    }
  }
  attr {
    key: "shared_name"
    value {
      s: ""
    }
  }
}
node {
  name: "x/Assign"
  op: "Assign"
  input: "x"
  input: "x/initial_value"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@x"
      }
    }
  }
  attr {
    key: "use_locking"
    value {
      b: true
    }
  }
  attr {
    key: "validate_shape"
    value {
      b: true
    }
  }
}
node {
  name: "x/read"
  op: "Identity"
  in

This is what happens when someone decides to be clever and use lazy loading to save one line of code.
On the other hand, the protobuf for the graph in lazy loading has 10 copies of the 
node “Add”. It adds a new node “Add” every time you want to compute z!

In [55]:
g = tf.Graph()
with g.as_default():
    x = tf.Variable(10, name='x')
    y = tf.Variable(20, name='y')

with tf.Session(graph=g) as sess:
    sess.run(tf.global_variables_initializer())
    for _ in range(10):
        sess.run(tf.add(x, y)) # # create the op add only when you need to compute it
    writer = tf.summary.FileWriter('./graph_2', sess.graph)
    writer.close()
    #print(sess.graph.get_operations())
    print(sess.graph.version)
    print(sess.graph.as_graph_def())

19
node {
  name: "x/initial_value"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 10
      }
    }
  }
}
node {
  name: "x"
  op: "VariableV2"
  attr {
    key: "container"
    value {
      s: ""
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
      }
    }
  }
  attr {
    key: "shared_name"
    value {
      s: ""
    }
  }
}
node {
  name: "x/Assign"
  op: "Assign"
  input: "x"
  input: "x/initial_value"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@x"
      }
    }
  }
  attr {
    key: "use_locking"
    value {
      b: true
    }
  }
  attr {
    key: "validate_shape"
    value {
      b: true
    }
  }
}
node {
  name: "x/read"
  op: "Identity"
  in